[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# gameplay update joker 

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "_pool[#_pool + 1] = v.key"
position = "before"
payload = '''
-- this joker is stupid lmao
local modded_jokers = SMODS.find_card('j_cere_gameplay_update')
if #modded_jokers > 0 then
    if v.mod then--string.sub(v.key, 1, 6) == 'j_cere' then
        print('ben')
        for i = 1, #modded_jokers do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end
local cere_jokers = SMODS.find_card('j_cere_ceres_joker')
if #cere_jokers > 0 then
    if string.sub(v.key, 1, 6) == 'j_cere' then
        print('ben')
        for i = 1, #cere_jokers do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end'''
match_indent = true


