[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effects.jokers.Xmult_mod then mult = mod_mult(mult*effects.jokers.Xmult_mod);extras.mult = true  end"
position = "after"
payload = '''
if effects.jokers.buf_Emult_mod then mult = mod_mult(mult^effects.jokers.buf_Emult_mod);extras.mult = true end
if effects.jokers.buf_Xchip_mod then hand_chips = mod_chips(hand_chips*effects.jokers.buf_Xchip_mod);extras.hand_chips = true end
if effects.jokers.buf_Echip_mod then hand_chips = mod_chips(hand_chips^effects.jokers.buf_Echip_mod);extras.hand_chips = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effect.Xmult_mod then mult = mod_mult(mult*effect.Xmult_mod);extras.mult = true  end"
position = "after"
payload = '''
if effect.buf_Emult_mod then mult = mod_mult(mult^effect.buf_Emult_mod);extras.mult = true end
if effect.buf_Xchip_mod then hand_chips = mod_chips(hand_chips*effect.buf_Xchip_mod);extras.hand_chips = true end
if effect.buf_x_chips then hand_chips = mod_chips(hand_chips*effect.buf_x_chips);extras.hand_chips = true end
if effect.buf_Echip_mod then hand_chips = mod_chips(hand_chips^effect.buf_Echip_mod);extras.hand_chips = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.FUNCS.check_for_buy_space = function(card)"
position = "after"
payload = '''
if card.ability.name == 'Laidback Joker' and not (#G.jokers.cards < (G.jokers.config.card_limit - 1) + ((card.edition and card.edition.negative) and 1 or 0)) then
  alert_no_space(card, card.ability.consumeable and G.consumeables or G.jokers)
  return false
end
'''
match_indent = true