[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if add and not G.GAME.banned_keys[v.key] then'''
position = 'before'
match_indent = true
payload = '''if G.GAME.modifiers.ortalab_only and _type ~= 'Seal' then
    if not v.mod or v.mod.id ~= 'ortalab' then
        add = false
    end 
end
'''

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if _pool_size == 0 then'''
position = 'before'
match_indent = true
payload = '''if _pool_size == 0 then
    _pool = EMPTY(G.ARGS.TEMP_POOL)
    if G.GAME.modifiers.ortalab_only then
        local new_pool = get_current_pool('Loteria')
        local replacement_key = pseudorandom_element(new_pool, pseudoseed('ortalab_only'))
        while replacement_key == 'UNAVAILABLE' do
            replacement_key = pseudorandom_element(new_pool, pseudoseed('ortalab_only_resample'))
        end
        if SMODS.ConsumableTypes[_type] and SMODS.ConsumableTypes[_type].default and G.P_CENTERS[SMODS.ConsumableTypes[_type].default] then
            _pool[#_pool+1] = SMODS.ConsumableTypes[_type].default
        elseif _type == 'Tarot' or _type == 'Tarot_Planet' then _pool[#_pool + 1] = replacement_key
        elseif _type == 'Planet' then _pool[#_pool + 1] = replacement_key
        elseif _type == 'Spectral' then _pool[#_pool + 1] = replacement_key
        elseif _type == 'Joker' then _pool[#_pool + 1] = "j_ortalab_jester"
        elseif _type == 'Demo' then _pool[#_pool + 1] = "j_ortalab_jester"
        elseif _type == 'Voucher' then _pool[#_pool + 1] = "v_blank"
        elseif _type == 'Tag' then _pool[#_pool + 1] = "tag_ortalab_rewind"
        else _pool[#_pool + 1] = "j_ortalab_jester"
        end
        _pool_size = 1
    end
end
'''